### ISSUE TITLE
version failed with return code 20 - 1.2.0 beta

### ISSUE THREAD

**Issue by tomse** [henrikstengaard/hstwb-installer#10]
after 1st reboot in winuae I get version failed.
happens with custom rom/wb and custom rom/cloanto wb

[new 1.txt](https://github.com/henrikstengaard/hstwb-installer/files/1595109/new.1.txt)

**Comment by tomse** [comment]
found the bug
setpatch does not return a version number in either WB packages, hence it crashes out.

**Comment by tomarkus** [comment]
I have the same issue with Roms and 3.1 WB from Amiga Forever 7 Plus. Any solution?

[Pic](https://imgur.com/a/mfJyw)

**Comment by tomse** [comment]
@tomarkus if you want to continue, just edit the startup-sequence remove or comment out the IF section around setpatch (before and after "setpatch quiet"

meaning have only "setpatch quiet" in that section

**Comment by tomarkus** [comment]
Works like a charm, thanks! :)

**Comment by henrikstengaard** [comment]
Fixed by moving failat 21 before version command is used, which allows it to fail qithout quitting
