### ISSUE TITLE
1.2.0 beta - doesn't detect AF emulators

### ISSUE THREAD

**Issue by tomse** [henrikstengaard/hstwb-installer#13]
1. The installer doesn't detect the emulators i.e. WinUAE from Amiga Forever.

2. you cannot go "back" without setting an emulator, even though it's been set manually previously. (just cosmetic)

**Comment by henrikstengaard** [comment]
Cloanto Amiga Forever WinUAE emulators are now autodetected and shown in the select emulator menu. Also the back option is added.
