### ISSUE TITLE
Installing Remove Games 4GB error

### ISSUE THREAD

**Issue by tomse** [henrikstengaard/hstwb-installer#16]
During setup errors occur. (see screenshot)
![capture](https://user-images.githubusercontent.com/1444539/36629192-e1fb334e-1952-11e8-9162-83e9ecb46367.JPG)

**Comment by tomse** [comment]
Deactivated the menu step for ocs menu..
I guess I'm missing something (user packages?)

**Comment by tomse** [comment]
manually creating Remove-Game-Entries folder in the right place fixed that problem.

**Comment by henrikstengaard** [comment]
It's my mistake. I had forgotten to properly rename a directory for EAB WHDLoad Games OCS Menu package.

It's fixed now and will be part of v1.2.0-BETA3
