### ISSUE TITLE
Problem with User Packages installation

### ISSUE THREAD

**Issue by obefocus** [henrikstengaard/hstwb-installer#19]
I'm using the latest provided 16gig image and i get this error message when proceeding with User Packages installation :
1) I have put all RetroPlay lha files in their corresponding directories :
C:\Temp\UserPackages\eab-whdload-demos
C:\Temp\UserPackages\eab-whdload-games
C:\Temp\UserPackages\eab-whdload-games_beta
So, 
in C:\Temp\UserPackages\eab-whdload-demos i have subdirectories called "#","A",..."Z" and in each of them the corresponding lha files
in C:\Temp\UserPackages\eab-whdload-games i have subdirectories called "#","A",..."Z" and in each of them the corresponding lha files
in C:\Temp\UserPackages\eab-whdload-games_beta i have lha files at this root directory
2) I have successfully executed "build_eab_whdload_install.cmd"
- All the entries for Games, Demos and beta games are found
3) When running hstwb-installer.uae the installation starts and i have this issue with USERPACKAGES :

- In the Device names status screen i have this :
WORKBENCHDIR : Present !
KICKSTARTDIR : Present !
USERPACKAGESDIR : Present !

===> So it looks like ok. 
- However after pressing ENTER to continue i get this :

Finding user packages in USERPACKAGESDIR :
list : unknown command
sed: can't open T: _userpackages1
done
No user packages found, skipping user package installation

I have the same issue either with Winuae of FS-UAE, The remaining steps for installation completes successfully, only the installation of USERPACKAGESDIR is failing.

Any idea ? Thanks

**Comment by henrikstengaard** [comment]
Yes, this has been fixed in latest version of HstWB Installer. Please try again with v1.2.0-BETA5.
