### ISSUE TITLE
ClassicWB 3.9 - no asyncwb

### ISSUE THREAD

**Issue by ryanfantus** [henrikstengaard/hstwb-installer#20]
Hi,

I chose to install OS3.9 and ClassicWB 3.9. I ran into two issues -

First, I was able to install this into too small a partition and ran out of space during the installer, it might be a good idea to require a 500mb DH0: partition for OS3.9.

Second, I don't recall seeing BB1+2 installed at any point, but assumed it was automatic. Now when I launch ClassicWB 3.9, it complains about missing AsyncWB. I believe this was in BB2...how can I confirm the boing bags installed? Did I miss a step?

Otherwise, excellent program! :) I'm going to experiment with adding OS3.1.4 compatibility (if I have time).

**Comment by henrikstengaard** [comment]
Some of the images has a 300MB DH0:, which works fine with Amiga OS 3.9. I agree, that it would be nice to have HstWB Installer show a warning message, if DH0: doesn't have enough free diskspace.

I have looked into the issue and reproduced the missing AsyncWB errors. If you choose to install Amiga OS 3.9 without Boing Bag 1 and 2 and install ClassicWB OS39, then it will give you AsyncWB errors.

Didn't you get the warning message before installing ClassicWB OS39 as attached?

![classicwb_os39_bb_warning](https://user-images.githubusercontent.com/9459668/55546057-c9c6a000-56ce-11e9-8351-3b2423451873.png)
![classicwb_os39_asyncwb_error](https://user-images.githubusercontent.com/9459668/55546066-cd5a2700-56ce-11e9-9f22-90da51a1c3f9.png)
