### ISSUE TITLE
Edit the names on the boot screen

### ISSUE THREAD

**Issue by blindguy** [henrikstengaard/hstwb-installer#29]
I'm not sure if this is an issue more like a how do I.

I am able to get most thigns going but is there a way to change the names on the boot screen?  For instance I have AGS2Games, AGS2Demos, HSTGames and HSTDemos.  Can I rename them to be somehting else or is ther a way int he install to tell it to use a different name?

This is AWESOME software!!! Thanks so MUCH!!

**Comment by henrikstengaard** [comment]
The boot menu is Amiga Boot Selector and as I recall you can enter it's configuration with F1 and change the options. I not sure it has a rename function, but then you need to add a new option and copy & rename it's script afterwards. These are located in DH0:S/AmigaBootSelector and once new options are added, empty scripts gets added there.

**Comment by blindguy** [comment]
@henrikstengaard that worked perfectly thansk so much,
I truly love this - I been making all kinds of new boot disks and playing aroudn for days!!
