### ISSUE TITLE
Prompt for LIBS/workbench.library  (1.4.2 installing 3.1.4 -> A500)

### ISSUE THREAD

**Issue by ryanm101** [henrikstengaard/hstwb-installer#38]
Getting a prompt to insert volume containing LIBS/workbench.library
I've all the 3.1.4 disks and the 3.1.4 ROM.

This seems to be caused due to the scripts copying in the os 3.1 files (I had only added the 3.1.4 disks) and adding them to fs-uae media list. 

I deleted the files from the directory and removed them from the UAE media list and this is resolved. 

I will look (doing my 1st build atm) once done and suspect `hstwb_image_setup.ps1` is to blame

**Comment by henrikstengaard** [comment]
Both HstWB Installer and hstwb_image_setup.ps1 script has been fixed with latest releases regarding icon.library and workbench.library files being loaded from Amiga OS 3.2 and 3.1.4 workbench and install disks.
