### ISSUE TITLE
RAM DISK icon not displaying properly after clean install of ClassicWB Full 3.1.4

### ISSUE THREAD

**Issue by lovrenco** [henrikstengaard/hstwb-installer#40]
![RAM_Disk](https://user-images.githubusercontent.com/5626489/103426614-092f6280-4bbb-11eb-8d65-584af1fb468f.PNG)

It is displaying Floppy icon instead of RAM disk icon. I tried installing several version ADV, FULL etc. Result is always the same.

**Comment by lovrenco** [comment]
I found a cause of this. There is no def_ramdisk.info in ENVARC:Sys/
I copied that file from HSTWB pack, which uses same set of Magic icons.

Also I added command to User-Startup, as shown on the photo. 

I get Ram Disk icon now on reboot, however it is "flat", there is no border around it. I will investigate some more.

![command](https://user-images.githubusercontent.com/5626489/103457926-94b40b00-4d03-11eb-8c24-b5591b9fe0e9.png)

**Comment by lovrenco** [comment]
This is how it looks now (ignore TempDir, I put icon there just for the test)

![Cwb_Full_with_icon](https://user-images.githubusercontent.com/5626489/103458017-5bc86600-4d04-11eb-828f-082124f6f576.png)

**Comment by lovrenco** [comment]
Add finally, I discovered that if you enable Scalos after default installation, you het RAM Disk icon normally, without any extra intervention (after restart).
However, if you turn Scaos off and reboot, you end up with other Ram Disk icon again. See photos. 

![ScalosNo](https://user-images.githubusercontent.com/5626489/103458324-34bf6380-4d07-11eb-9748-f75afb2fe9d3.png)
![ScalosYes](https://user-images.githubusercontent.com/5626489/103458327-3557fa00-4d07-11eb-8b95-db3010bca0a6.png)

**Comment by henrikstengaard** [comment]
RAM disk icons for ClassicWB packages have been fixed with latest releases of HstWB Installer.
