### ISSUE TITLE
Pre-Made image for Raspsberry PI

### ISSUE THREAD

**Issue by actraiser30** [henrikstengaard/hstwb-installer#42]
Hello is it possible to put in the downloads: https://hstwb.firstrealize.com/download

The Amibian v1.4.1001 img preconfigured with HstWB self install HDF image v1.5.1 ??

for the Raspberry pi

Thanks

**Comment by henrikstengaard** [comment]
Pre-made images for Raspberry Pi with HstWB Installer are no longer created as they are too cumbersume to update and maintain. Instead HstWB Installer for Raspberry Pi offers an install scripts, so it can be installed on any Raspberry Pi image. Currently only Raspberry Pi OS Lite has been tested.

Amibian is no maintained and therefor HstWB Installer for Amibian is now also obsolete and also no longer maintained.

Maybe HstWB Installer for Raspberry Pi works on the obsolete Amibian images, see wiki page https://github.com/henrikstengaard/hstwb-installer/wiki/HstWB-Installer-for-Raspberry-Pi for installation for installation, but there's no guarantee.
