### ISSUE TITLE
Write protected error

### ISSUE THREAD

**Issue by symbios24** [henrikstengaard/hstwb-installer#43]
Hello in a Raspberry Pi 3 with amibian 1,4 and latest hstwb 1.5.1 
Upon finalizing the installation of AmigaOS 3.2
I get a message in box saying: 

System Request
Volume
KickstartDir
is write protected

I only have two options in the box retry or cancel
Retry does nothing

Is thia a bug ??
Or i did anything wrong?
Im installing AmigaOS 3.2 from adf disks
But i also have the AmigaOS 3.2 iso should i try that?

![IMG_20210928_165742](https://user-images.githubusercontent.com/10866601/135101645-94cb2f58-eb69-41f8-8f71-f40d3d7ba7a2.jpg)

Update: if i press cancel it continues the installation,i get this message again a couple of times i press cancel and continues,finishes and the amigaOS 3.2 loads fine
Must be a bug e?
Strange coz i dont do it from windows to give me write protection errors
Do you know what's wrong and how to fix it??

Thanks

**Comment by henrikstengaard** [comment]
This error has been fixed with latest release v1.6.3

**Comment by Juppstein** [comment]
I get this error  when running the hst installer via FS-UAE in Unbuntu 22.04 LTS
