### ISSUE TITLE
Getting "Can't subtract" errors

### ISSUE THREAD

**Issue by PlatypusWithCheese** [henrikstengaard/hstwb-installer#9]
I'm getting "Can't subtract" errors both in WinUAE and on real hardware.
(also the installer is also so broken it just errors out)
![cansubtract](https://user-images.githubusercontent.com/8530385/32138423-ba7fb506-bc32-11e7-9cc0-9b6a585a8feb.png)

**Comment by henrikstengaard** [comment]
I recall having seen similar errors using Kickstart 3.0. Which Kickstart rom are you using?

**Comment by PlatypusWithCheese** [comment]
ah that might be it because i have Kickstart 3.0
